name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py
          
          cat metrics.txt >> report.md
          echo "![](./plot.png)" >> report.md
          #cml-comment confusion_matrix.png --md --title 'confusion-matrix' >> report.md # la mayoria de comandos cml no funciona
          echo feature_importance.png --md >> report.md
          cml-send-comment report.md  # hacen lo mismo, cml comment create and cml-send